[package]
name = "cardgame-rs"
version = "0.1.0"
authors = ["Lasm Gratel <lasm_gratel@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"